          
- name: Copy multiple files handler
  copy:
    src: "files/{{ item }}"
    dest: "/var/www/html/{{ item }}"
  loop: "{{ file_list }}"
  notify: my_handler
  changed_when : true



- name: my_handler
  service:
   name: "{{package_name}}"
   state: restarted
   use: service
    
 